export {
  AUDIT_LIMITS,
  auditConfigSchema,
  parseAuditConfig,
  safeParseAuditConfig,
  type AuditConfig,
  type AuditConfigInput,
} from "./config/audit-config.js";
export {
  AUDIT_SCHEMA_VERSION,
  EVIDENCE_SOURCES,
  FINDING_CATEGORIES,
  FINDING_SEVERITIES,
  PAGE_TYPES,
  SCANNERS,
  VIEWPORTS,
  auditEvidenceSchema,
  auditFindingSchema,
  auditOutputsSchema,
  auditResultSchema,
  auditSummarySchema,
  evidenceSourceSchema,
  findingCategorySchema,
  findingCountsSchema,
  findingSeveritySchema,
  pageTypeSchema,
  scannedPageErrorSchema,
  scannedPageSchema,
  scannerSchema,
  viewportSchema,
} from "./core/schemas.js";
export type {
  AuditEvidence,
  AuditFinding,
  AuditOutputs,
  AuditResult,
  AuditSummary,
  EvidenceSource,
  FindingCategory,
  FindingCounts,
  FindingSeverity,
  PageType,
  ScannedPage,
  ScannedPageError,
  ScannerName,
  Viewport,
} from "./core/types.js";
export {
  createAuditId,
  createAuditOutputDirectories,
  type AuditIdDependencies,
  type AuditOutputDirectories,
} from "./infrastructure/audit-output.js";
export {
  REDACTED_LOG_PATHS,
  createLogger,
  type CreateLoggerOptions,
} from "./infrastructure/logger.js";
